name: Deploy Theme to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Shopify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
        
      - name: Shopify Target Store and Push
        run: shopify theme push --path=. --unpublished
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
